# syntax=docker/dockerfile:1

ARG GO_VERSION=1.26.4
FROM golang:${GO_VERSION}

ENTRYPOINT []
WORKDIR /fivetran-source

RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip \
    && rm -rf /var/lib/apt/lists/*
