services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    volumes:
      - .:/fivetran-source
    working_dir: /fivetran-source
  licensing:
    build:
      context: containers/licensing
    volumes:
      - .:/work
    working_dir: /work
