# syntax=docker/dockerfile:1

ARG GO_VERSION=1.21.3
FROM pscale.dev/wolfi-prod/go:${GO_VERSION} AS build

ARG GH_TOKEN
ENTRYPOINT []
WORKDIR /fivetran-source
COPY . .

RUN go mod download
RUN make build-server
